# PteroStats Configuration File
# Need help? Join our Discord server: https://discord.com/invite/ultimedev
version: 9 # Warning: Do not change this unless you know what you are doing!

# App/Bot Presence Configuration
presence:
  enable: true # Enable or disable app presence (true/false).
  text: "UltimeDev" # The status text shown by the app.
  type: "watching" # Available types: 'watching', 'playing', 'listening', 'competing'. (Note: 'streaming' is currently unsupported)
  status: "dnd" # Available types: 'online', 'idle', 'dnd', or 'invisible'

# Discord Channel and Refresh Timing Configuration
refresh: 60 # Interval in seconds for refreshing the panel's stats.
timeout: 5 # Timeout in seconds for panel and node responses. Adjusting this will affect the overall refresh time.

# Message and Embed Configuration
# To disable an option, leave the value as an empty string: ''
message:
  content: "Voici le status de l'hébergeur pterodactyl du serveur UltimeDev" # Custom content for app messages.
  attachment: "https://discord.com/channels/1337796344651317329/1339754137214124132/1342095482633064449" # Attachments will delay stats refresh since they are uploaded first.

embed:
  panel:
    author:
      name: "Status Hébergeur" # Author name for the panel embed.
      icon: "" # Icon URL for the author of the panel embed.
    title: "Statistiques hébergeur" # Title of the panel stats embed.
    description: "Prochaine mise à jour dans {{time}}" # Description for the panel. {{time}} will display the next refresh time.
    timestamp: true # Show the timestamp in the embed (true/false).
    color: "5865F2" # Embed color in hex format.
    footer:
      text: "UltimeDev" # Footer text. Set to '' to disable.
      icon: "https://cdn.discordapp.com/attachments/1298760976501571655/1342073304722178048/242380c9f8deb6fcecf97ac7042bed41.webp?ex=67b84eaa&is=67b6fd2a&hm=54b50123911dff1355aa137573d2115ad6d517161d9f3a0176179cc28dce9055&" # Footer icon URL.
    thumbnail: "" # Thumbnail URL for the embed.
    image: "" # Image URL for the embed.

  nodes:
    author:
      name: "Node" # Author name for the nodes embed.
      icon: "" # Icon URL for the author of the nodes embed.
    title: "Statistiques Nodes" # Title for the nodes stats embed.
    description: "" # Description for the nodes stats embed. Can be left empty.
    timestamp: true # Include a timestamp in the nodes embed (true/false).
    color: "5865F2" # Embed color in hex format.
    footer:
      text: "UltimeDev" # Footer text for nodes stats.
      icon: "https://cdn.discordapp.com/attachments/1298760976501571655/1342073304722178048/242380c9f8deb6fcecf97ac7042bed41.webp?ex=67b84eaa&is=67b6fd2a&hm=54b50123911dff1355aa137573d2115ad6d517161d9f3a0176179cc28dce9055&" # Footer icon URL.
    thumbnail: "" # Thumbnail URL for the nodes stats embed.
    image: "" # Image URL for the nodes stats embed.

# Message Button Configuration
button:
  enable: true # Enable or disable buttons in messages.
  row1:
    - label: "Lien du pterodactyl" # Label for the first button.
      url: "https://panel.ultimedev.fr" # URL for the first button.
#    - label: "Dashboard" # Remove "#" at the start of the line to use this button
#      url: "https://dash.example.com" # Remove "#" at the start of the line to use this button
#  row2: # Remove "#" at the start of the line to use this row
#    - label: "Backup Panel"
#      url: "https://panel2.example.com"
#    - label: "Backup Dashboard"
#      url: "https://dash2.example.com"

# Status Message Configuration
# How to use Custom Emoji: https://discord.com/invite/ultimedev
status:
  online: "<:1331598111260540928:1341186527543300188> En Ligne" # Status message for when a node is online.
  offline: "<:1331598113751826505:1341186539052597345> Hors Ligne" # Status message for when a node is offline.

# Node Settings
# How to get Node ID: https://discord.com/invite/ultimedev
nodes_settings:
  blacklist: [] # Add node IDs to exclude them from the status embed (e.g., blacklist: [1]).
  details: true # Show node details such as memory and disk usage (true/false).
  servers: true # Show server details (true/false).
  allocations_as_max_servers: false # Show allocations as max servers (true/false).
  host: true # Show node host (true/false).
  unit: "byte" # Resource Unit, Available types: "byte" or "percentage".
  uptime: true # Show node uptime (true/false).
  limit: 100 # Change how much node can will be displayed.

# Panel Users and Servers Settings
panel_settings:
  status: true # Display panel stats above node stats (true/false).
  host: true # Show panel host (true/false).
  uptime: true # Enable or disable node uptime (true/false).
  servers: true # Display servers count (true/false).
  users: true # Display users count (true/false).

# Notifier Configuration
# How to use notifier: https://discord.com/invite/ultimedev
notifier:
  enable: true # Enable or disable notifier.
  webhook: "" # Discord Webhook URL for the notifier.
  embed:
    author:
      name: "UltimeDev" # Author name for the notifier embed.
      icon: "" # Icon URL for the author of the notifier embed.
    timestamp: true # Include a timestamp in the notifier embed (true/false).
    footer:
      text: "UltimeDev" # Footer text for notifier stats.
      icon: "https://cdn.discordapp.com/attachments/1298760976501571655/1342073304722178048/242380c9f8deb6fcecf97ac7042bed41.webp?ex=67b84eaa&is=67b6fd2a&hm=54b50123911dff1355aa137573d2115ad6d517161d9f3a0176179cc28dce9055&" # Footer icon URL.
    thumbnail: "" # Thumbnail URL for the notifier stats embed.
    image: "" # Image URL for the notifier stats embed.

# Error Logging Configuration
# Enable logging to console if servers go offline, useful for debugging.
log_error: false # Set to true to enable error logging (true/false).